-- 01_users_and_privileges.sql
-- Run as SYSDBA (after setting container)

-- Optional cleanup
BEGIN EXECUTE IMMEDIATE 'DROP USER MANAGER CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER USER1 CASCADE';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER USER2 CASCADE';   EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Create users
CREATE USER MANAGER IDENTIFIED BY "123";
CREATE USER USER1 IDENTIFIED BY "u1";
CREATE USER USER2 IDENTIFIED BY "u2";

-- Basic sessions
GRANT CREATE SESSION TO MANAGER;
GRANT CREATE SESSION TO USER1;
GRANT CREATE SESSION TO USER2;

-- Manager capabilities (lab)
GRANT CREATE USER, ALTER USER, DROP USER TO MANAGER;
GRANT GRANT ANY PRIVILEGE TO MANAGER; -- lab-only

-- USER1 capabilities (schema owner)
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO USER1;

-- Quotas
ALTER USER MANAGER QUOTA UNLIMITED ON USERS;
ALTER USER USER1    QUOTA UNLIMITED ON USERS;
ALTER USER USER2    QUOTA UNLIMITED ON USERS;
