-- 03_cross_schema_grants.sql
-- Run as SYSDBA (after setting container)

-- Allow MANAGER to grant object privileges in lab setup
GRANT GRANT ANY OBJECT PRIVILEGE TO MANAGER;
GRANT GRANT ANY PRIVILEGE TO MANAGER;

-- Cross-schema grants for USER2 (application user)
GRANT INSERT, SELECT ON USER1.STUDENTS   TO USER2;
GRANT INSERT, SELECT ON USER1.COURSES    TO USER2;
GRANT INSERT, SELECT ON USER1.REGISTER   TO USER2;
GRANT INSERT, SELECT ON USER1.PROFESSORS TO USER2;

-- Bonus part uses update
GRANT UPDATE ON USER1.STUDENTS TO USER2;
