-- 05_sequences.sql
-- Run as USER1

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE AUDITTRAIL_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE WARNINGS_SEQ';   EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE AUDITTRAIL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE WARNINGS_SEQ   START WITH 1 INCREMENT BY 1;
